# Generated by Django 5.2.8 on 2026-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-time_create'], name='main_movie_time_cr_idx'),
        ),
    ]
