# Generated by Django 6.0.4 on 2026-05-14 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='main.movietag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='technicalspecs',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.movie', verbose_name='Фильм'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-time_create'], name='main_movie_time_cr_21bfb2_idx'),
        ),
    ]
