# Generated by Django 5.2.8 on 2026-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260425_2242'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='main_movie_time_cr_idx',
        ),
    ]
