# Generated by Django 5.2.8 on 2026-04-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_movie_main_movie_time_cr_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-time_create'], name='main_movie_time_cr_21bfb2_idx'),
        ),
    ]
