# Generated by Django 4.2.1 on 2026-04-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_alter_movie_slug_movie_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='main.category', verbose_name='Категория'),
        ),
    ]
