# Generated by Django 4.2.1 on 2026-05-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_movietag_movie_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(default='4K', max_length=50, verbose_name='Разрешение')),
                ('camera', models.CharField(max_length=100, verbose_name='Камера')),
                ('color_space', models.CharField(max_length=50, verbose_name='Цветовое пространство')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Технический паспорт',
                'verbose_name_plural': 'Технические паспорта',
            },
        ),
    ]
